== Proces vyjádření k území

1. Na podatelnu IPR Praha přijde dokument týkající se agendy kanceláře KPÚ. Pracovník podatelny eviduje dokument jako příchozí poštu do E-spis a zároveň importuje do SpIS.
3. Pověřený uživatel SpISu dle druhu importovaného dokumentu provede přiřazení typu dokumentu (**Vyjádření ke stavebním záměrům**, Vyjádření k záměru EIA**, **Koncepční vyjádření k záměru na veřejné prostranství**, **Námitky** atd.), zákres území do mapy a dle charakteru dokumentu (pouze na vědomí, žádost o vyjádření) pošle k vyjádření všem pověřeným odborným pracovníkům, nebo na vědomí všem dotčeným.
4. V případě žádosti o vyjádření Každý oslovený odborný uživatel vyplní svou část vyjádření, potvrdí či nechá schválit.
5. Po kompletaci všech částí vyjádření je pověřený uživatel upozorněn a kompletní znění pošle ke schválení a podpisu oprávěnému nadřízenému.
6. Po schválení nadřízeným je vytvořena tisková sestava opatřená podpisy odpovědných uživetlů a exportována do E-spisu k odeslání žadateli.

V současné době není na IPR Praha žádné koncepční řešení pro proces zpracování žádostí o vyjádření a odpovědí na ně, proto bude tato agenda součástí implementační analýzy.

== Speciální požadavky na SpIS při zákresu lokalizace

IPR Praha disponuje centrální databází záměrů v území, do které bude přebírat i informace z vyjádření ze SpIS následujícím způsobem. SpIS bude s databází propojen na úrovni předávání informací vybraných údajů z Vyjádření a doplněním dalších informací přímo o záměru stavby. V mapovém okně SpIS bude k zákresu lokalizace Vyjádření záměru využita předpřipravená vektorová feature vrstva z geodatabáze IPR Praha. Tato vrstva obsahuje připravenou atributovou tabulku, do které se po zákresu lokalizace do mapy budou ukládat hodnoty dvěma způsoby: přebráním již vyplněných vybraných informací z Vyjádření a následným ručním vyplněním doplňujících atributů před uložením mapové vrstvy. Všechny informace se po uložení zakresleného prvku do mapy tímto postupem uloží přímo do geodatabáze IPR Praha. Ve SpISu zůstanou nadále jen informace související s Vyjádřením. Atributy související se záměrem budou nadále dostupné v infowindow při kliknutí na prvek v mapě.
