= Správní informační systém: Technická specifikace
:numbered:
:icons: font
:lang: cs
:note-caption: Poznámka
:warning-caption: Pozor
:toc-title: Obsah
:toc: left

== Úvod

Správní informační systém, zkráceně _SpIS_ je otevřený nástroj pro vedení elektronických evidencí. Měl by zpřehlednit správu věcí a to zejména těch veřejných. V praxi bude tedy evidovat doklady a další dokumenty.

WARNING: Správa věcí veřejných... Spíše by měl zpřehlednit správní agendy společné pro všechny organizace, zvláště ty pro ty veřejné.

Výběr z funkcí, které očekáváme v prvních verzích:

Hierarchické pracovní struktury::
Rozklad předmětu plnění na jednotlivé dodávané výsledky (což jsou pro nás dokumenty) v předepsané hierarchii (dle typu projektu). Tento postup se jinde označuje pojmem link:https://cs.wikipedia.org/wiki/Work_breakdown_structure[WBS].

Editor dokumentů::
Nástroj pro vytváření a úpravy dokumentů, představující uživatelské rozhraní uzpůsobené jejich konkrétním typům. Využívá zásuvné moduly, které realizují dílčí komponenty rozhraní. Každý typ dokumentu popisuje, jaké komponenty se mají pro jeho pole využít.

Přehledy::
Vhodně zvolené přehledy čerpající z projektů a dalších evidencí. Pro jejich zobrazení se využívají komponenty realizované jako zásuvné moduly. Tyto komponenty se provazují s konkrétními daty, čímž vznikají pohledy, které se dále seskupují do témat.

Oprávnění::
Pružný systém oprávnění založený na uživatelských rolích a organizačních jednotkách umožňuje pracovat pouze s těmi dokumenty a na těch projektech, které se uživatelů týkají.

SpIS bude napojen na vybrané další informační systémy, ze kterých bude čerpat podklady a do kterých bude předávat výstupy nebo dílčí dokumenty. Napojení bude realizováno prostřednictvím datové vrstvy, tedy v databázi.

WARNING: Nejen v databázi. Potenciálně bude potřeba volat nějaké služby, což se jaksi pomalu, ale jistě dostáváme k ESB.

<<<

== Hierarchické pracovní struktury

Hierarchické pracovní struktury jsou formou vedení *projektu*. Tato forma spočívá v postupném vytváření a schvalování dokumentů, které dokládají provedené úkony. dokumenty mohou být v různých stavech, ale zejména bývají *Rozpracované*, časem *Dokončené* a výjimečně *Provizorní*.

Rozpracované::
Dokumenty, které ještě nejsou hotové a nelze se na ně spoléhat.

Dokončené::
Dokumenty, které jsou hotové a schválené zodpovědnou osobou. Tato osoba ručí za jejich správnost a platnost. Ostatní se na ně mohou obvykle bez obav spolehnout.

Provizorní::
Dokumenty, které jsou hotové, ale nejsou schválené zodpovědnou osobou. Pokud se na ně pracovníci spoléhají, přebírají tím na sebe riziko, které jinak leží na zodpovědné osobě.

Dokumenty ve struktuře na sobě vzájemně závisí. Některé dokumenty tvoří kořeny, na kterých již žádné další dokumenty nezávisí. Na jiných dokumentech závisí jeden i více dokumentů. V podstatě se jedná o acyklický orientovaný graf.

V praxi může hierarchická struktura vypadat například takto (šipky značí závislost):

[plantuml,align="center"]
....
@startuml
rectangle "faktura" <<Faktura>> #9999ff
rectangle "protokol 1" as protokol_1 <<Akceptační protokol>> #99ff99
rectangle "protokol 2" as protokol_2 <<Akceptační protokol>> #ffff99
rectangle "nabídka" <<Nabídka>> #99ff99
rectangle "poptávka" <<Poptávka>> #99ff99
rectangle "specifikace" <<Specifikace>> #99ff99

poptávka -d-> specifikace
faktura -d-> nabídka
faktura -d-> protokol_1
faktura -d-> protokol_2
protokol_1 -d-> specifikace
protokol_1 -d-> nabídka
protokol_2 -d-> specifikace
protokol_2 -d-> nabídka
nabídka -d-> poptávka
@enduml
....

V příkladu je `protokol 2` nedokončený, ale pracovník zodpovědný za schválení faktury ho označil za provizorní. To proto, aby mohl vytvořit provizorní fakturu a mohla proběhnout platba. Pokud se zmýlil a pracovník zodpovědný za `protokol 2` tento nedokončí, mohou být vyvozeny důsledky.

Z důvodu průkaznosti nelze dokončené dokumenty měnit. Pokud by se tak mělo stát, je vytvořen dokument nový, který ten původní nahradí v jeho roli. Pokud se na předchozí dokument jiný dokument spoléhá, je považován za neplatný. Uveďme si příklad:

[plantuml,align="center"]
....
@startuml
rectangle "faktura" <<Faktura>> #ff9999
rectangle "protokol" <<Akceptační protokol>> #9999ff
rectangle "specifikace" <<Specifikace>> #99ff99

faktura -d-> protokol
protokol -d-> specifikace

note right of faktura: verze 1
note right of protokol: verze 2
@enduml
....

V příkladu došlo k tomu, že byla v důsledku aktualizace dokumentu `protokol` zneplatněna aktuální verze dokumentu `faktura`. V této situaci jsou v podstatě jen dvě možnosti, jak postupovat správně:

1. Vrátit se k předchozí verzi dokumentu `protokol`, kterou systém uchovává.
2. Schválit novou verzi dokumentu `protokol` a následně vytvořit novou verzi dokumentu `faktura`.

=== Typy projektů

Každý projekt je opatřen popisem své hierarchické struktury. Protože si jsou některé projekty ve své struktuře velmi podobné, definujeme pojmenované typy projektů. Tyto typy reprezentují strukturu, ze které je možné v případě potřeby rychle vyjít. Jsou to tedy určité šablony.

V případě potřeby je možné strukturu aktivního projektu změnit a dokumenty přeuspořádat do nových rolí. Stejně tak je možné do struktury vložit již existující dokumenty, pokud tak nedojde k porušení jejich vazeb na závislosti.

=== Sekce a Témata

Za účelem snazší orientace uživatelů v systému jsou projekty a jejich typy rozčleněny do sekcí a témat. Ve stejném členění jsou zařazeny také přehledy, což usnadňuje nalezení nástrojů pro zásahy do dat, která přehledy představují. Zároveň toto členění usnadňuje kontrolu výsledků aktivních projektů -- po dokončení práce na projektu se uživatel snadno vrací na přehledy daného tématu.

WARNING: Pokud čtu sekvenčně, v tuto chvíli nevím, co je téma a sekce. Je vhodné odkázat.
<<<

== Dokumenty

Pod pojmem dokument rozumíme strukturovaná, strojová data, se kterými uživatel nakládá přímo v systému. Tyto dokumenty často mívají přílohy, což jsou nestrukturovaná data (často různé formátované texty, tabulky či obrázky), které vznikají mimo systém a jsou do něj pouze vkládány.

Dokumenty mají kromě vnitřní struktury také takzvané závislosti a díky nim pak tvoří určité vnější struktury. Tyto závislosti jsou dokumentům vlastní ve všech projektech, kterých jsou součástí.

=== Typy dokumentů

Typy dokumentů shrnují vnitřní strukturu, závislosti, použité komponenty uživatelského rozhraní a další vlastnosti instancí (tedy dokumentů) do jednoznačného pojmenování. V příkladech výše jsme zatím viděli například typy nazvané `Faktura` nebo `Akceptační protokol`.

==== Závislosti

Dokumenty mohou záviset pouze na jiných dokumentech, a to vždy v určitých rolích. Pro ilustraci:

[plantuml,align="center"]
....
@startuml
rectangle "zápůjčka" <<Zápůjčka>> #9999ff
rectangle "předání 1" as předání_1 <<Předávací protokol>> #99ff99
rectangle " " as předání_2 <<Předávací protokol>> #dddddd

zápůjčka -d-> předání_1 : vstupní
zápůjčka -d-> předání_2 : výstupní

note right of zápůjčka
  Rozpracovaný dokument,
  jejž zatím nelze dokončit.
end note

note bottom of předání_2
  Neexistující dokument.
end note
@enduml
....

V příkladu je předávací protokol použit nejprve pro dokumentaci zahájení zápůjčky věci a následně bude použit pro dokumentaci jejího navrácení. Pro vyložení závislého dokumentu `zápůjčka` je podstatné tyto dva protokoly od sebe odlišit.

Oproti instancím (dokumentům) mohou typy záviset pouze na dalších typech (nebo typových třídách, které jsou vysvětleny níže). Typy pro příklad výše budou vypadat například následovně:

[plantuml,align="center"]
....
@startuml
skinparam monochrome true
skinparam padding 3

rectangle "zápůjčka" <<Zápůjčka>>
rectangle "předání 1" as předání_1 <<Předávací protokol>>
rectangle "předání 2" as předání_2 <<Předávací protokol>>

zápůjčka -d-> "{1,1}" předání_1 : vstupní
zápůjčka -d-> "{1,1}" předání_2 : výstupní
@enduml
....

Za povšimnutí stojí uvedení dokumentů, které by měly být přítomny, ale v příkladu výše zatím schází. Také jsou zde u rolí uvedeny kvantifikátory.

==== Kvantifikace

Závislosti je nutné kvantifikovat. V určité roli může vystupovat konkrétní počet dokumentů. Uveďme si příklad struktury dokumentů:

[plantuml,align="center"]
....
@startuml
rectangle "rozpočet" <<Rozpočet>> #9999ff
rectangle "návrh 1" as návrh_1 <<Dílčí návrh rozpočtu>> #99ff99
rectangle "návrh 2" as návrh_2 <<Dílčí návrh rozpočtu>> #99ff99
rectangle "návrh 3" as návrh_3 <<Dílčí návrh rozpočtu>> #9999ff

rozpočet -d-> návrh_1 : dle návrhu
rozpočet -d-> návrh_2 : dle návrhu
rozpočet -d-> návrh_3 : dle návrhu
@enduml
....

Ve struktuře se vyskytuje trojice dokumentů se shodným typem ve shodné roli. Jak budou vypadat typy pro tuto strukturu? Patrně následovně:

[plantuml,align="center"]
....
@startuml
skinparam monochrome true
skinparam padding 3

rectangle "rozpočet" <<Rozpočet>>
rectangle "návrh" <<Dílčí návrh rozpočtu>>

rozpočet -d-> "{1,}" návrh : dle návrhu
@enduml
....

Kvantifikátor `{1,}` zde značí přítomnost alespoň jednoho dokumentu daného typu v dané roli. Je však možné specifikovat libovolný rozsah, tedy například `{,}` nebo `{0,}` pro libovolný počet dokumentů, `{1,3}` pro jeden až tři dokumenty a `{,5}` nebo `{0,5}` pro až pět dokumentů.

==== Typové třídy

Typové třídy popisují dílčí strukturu dokumentů tak, aby mohlo dojít k použití více typů dokumentů ve stejné roli. Upravují jak strukturu typů dané třídy, tak i jejich závislosti.

Můžeme si například zavést typové třídy `Mající výši plnění (x)` a `Mající termín realizace (x)`, které popisují části schématu dokumentu, ve kterém předepisují přítomnost finanční částky s určitým významem a dále termínu, kdy dojde k nějaké realizaci. S pomocí těchto typových tříd pak můžeme popsat některé závislosti obecněji. Například:

[plantuml,align="center"]
....
@startuml
skinparam monochrome true
skinparam padding 3

rectangle "plán" <<Plán výdajů>>
rectangle "výdaj" <<Pro d, pokud platí\n Mající výši plnění (d),\n Mající termín realizace (d),\n pak libovolné d.>>

plán -d-> "{,}" výdaj : zahrnuje
@enduml
....

Pokud typy dokumentů `Plánovaná investice` a `Plánovaný provozní výdaj` implementují obě tyto typové třídy, pak je možné typy z předešlého případu splnit například následující strukturou:

[plantuml,align="center"]
....
@startuml
rectangle "plán" <<Plán výdajů>> #99ff99
rectangle "výdaj 1" as výdaj_1 <<Plánovaná investice>> #99ff99
rectangle "výdaj 2" as výdaj_2 <<Plánovaný provozní výdaj>> #99ff99

plán -d-> výdaj_1 : zahrnuje
plán -d-> výdaj_2 : zahrnuje
@enduml
....

Termín typová třída se hojně vyskytuje v kontextu programovacího jazyka Haskell. Typové třídy v Haskellu ale neposkytují stejný polymorfismus jako typové třídy popsané výše. V Haskellu by musely být oba výdaje v příkladu zcela stejného typu.

==== Schéma

=== Komponenty

WARNING: Komponenty...

<<<

== Přehledy

=== Pohledy

Pohled může být využit ve více tématech. Každý pohled je určitého typu, což určuje to, jaká data dokáže prezentovat a zároveň způsob, jakým tak činí.

Pokud autor daného typu pohledu vytvořil nástroj pro zobrazení mapových vrstev s vyznačenými body, je možné s jeho pomocí zobrazovat prostorová data. Pokud se jedná o nástroj pro zobrazení tabulky, je možné s jeho pomocí zobrazovat data relační a tak dále.

Obsah pohledu je dán popisem tématu, ve kterém je použit. Součástí tohoto popisu je i soubor dotazů do databáze, prostřednictvím kterých dojde k získání zobrazovaných dat. Tyto dotazy jsou parametrizovány hodnotami, které zvídavý uživatel mění při prohlížení.

=== Témata

WARNING: Uskupení pohledů, součást sekce. Obsahuje i seznam šablon k zahájení projektů.

=== Sekce

WARNING: Základní organizační členění.

<<<

== Model oprávnění
Model oprvánění je v systému navržen ve dvou rovinách a to v rovině oprávnění k typům dokumentů a způsobům, jak s ním nakládat (oprávnění), a v rovině původu dokumentu (obor působnosti). Kompozice množin oprávnění a oborů působnosti se nazývá role. Uživatel může vystupovat ve více rolích, přičemž platí, že cokoliv mu jedna role povolí, nemůže mu jiná zakázat a to z důvodu, že oprávnění jsou přiřazována explicitně (tj. implicitně je jakákoliv interakce zakázana).

=== Oprávnění

Každý dokument má v rámci projektu definovány stavy, v nichž se může nacházet. Oprávnění v tomto případě znamená, že daná role může s danými typy dokumentů operovat do nějaké úrovně a může je tak např. rozpracovat a učinit provizorními, nikoliv však dokončit.
Speciálním typem oprávnění je pak možnost určité typy dokumentů podepsat. Při podepisování není možné dokument již nijak měnit, podpisem lze pouze vyjádřit svůj úplný souhlas s obsahem daného dokumentu.

=== Obory působnosti

Obor působnosti sdružuje dokumenty, se kterými manipulují určité okruhy osob a to zpravidla takové, které jsou zařazeny v jedné organizační jednotce. Implicitně je každý uživatel zařazen do alespoň jedné organizační jednotky. Z takovéhoto zařazení vyplývají obory působnosti pro všechna oprávnění, tedy nikoliv jen pro ta, která jsou explicitně definovaná v roli.

Uveďme si příklad. Nechť existuje role "Majetkář", která definuje oprávnění k dokumentům typu "Zařazovací list" a "Předávací protokol pracovních pomůcek". Nechť je definováno, že existuje více "Majetkářů", z nichž někteří evidují o kancelářských potřebách, židlích, stolech, stolních větrácích apod. a jiní evidují o kancelářské výpočetní technice.
První i druhá skupina má přiřazenu stejnou roli, ale každý z nich je zařazen v jiné organizační jednotce. Za majetek každého z nich odpovídá jiný organizační celek. Není však třeba definovat role specifické pro každý z těchto celků, postačí implicitní přiřazení osoby do oboru působnosti.

=== Uživatelské role

Uživatelské role představují oprávnění k provádění množiny úkonů nad množinou typů dokumentů v rámci množiny organizačních jednotek. Libovolný uživatel může vystupovat v řadě rolí.

=== Zvaní do projektů

Po vytvoření projektu lze na základě typu projektu resp. dokumentů nutných k jeho dokončení sestavit seznam rolí, které na projektu musejí spolupracovat, aby jej bylo možné dokončit. Autor projektu může v jakékoliv chvíli povolit přístup daným rolím v tomto seznamu, čímž dojde k vyrozumění patřičných uživatelů v dané roli.
Současně je možné pozvat k projektu explicitně definované role či konkrétní uživatele. Tito uživatelé, nebudou-li příslušní k některé z rolí, které se projektu účastní, budou moci operovat pouze s dokumenty, které budou zpravidla přílohou dokumentů nutných k dopracování projektu. Typickým příkladem je doplnění funkční specifikace od odborného útvaru, kde předmětem nákupu je komodita jíž bude účelně využivat jiný útvar, a který tedy bude řešit proces nákupu.

<<<

== Implementační detaily

=== Architektura

[plantuml,align="center"]
....
@startuml
left to right direction

package "SpIS" {
  () HTTP
  HTTP -u- [Aplikace]

  database "DB"
  () SQL
  [Aplikace] -l-> SQL
  [DB] - SQL

  database "Politiky"
  Politiky -u-> [Aplikace]
}

node "PC" {
  [Prohlížeč] -> HTTP
  [Prohlížeč] .l.> [Pečetidlo]
  [Pečetidlo] -> HTTP
}

actor :Uživatel:

:Uživatel: - [Prohlížeč]
:Uživatel: - [Pečetidlo]

cloud "Externí systémy" {
  [ ] <<ERP a další...>> as Ext1
  [Ext1] -> SQL
}
@enduml
....

Uživatelé budou se SpISem komunikovat pomocí webového rozhraní, spuštěném v běžném webovém prohlížeči. Pro účely elektronického podepisování bude na jejich zařízeních nasazena další aplikace, ve schématu označená jako _Pečetidlo_.

Jak naznačuje schéma výše, _Aplikace_ samotná je běhovým prostředím pro jakési _Politiky_. Ty vytváří programátoři a popisují jimi nejen strukturu dokumentů, které se ve _SpISu_ vyskytují, ale také jejich vzájemné vazby v projektech, použité prvky uživatelského rozhraní a další rysy systému vlastní organizaci, které systém využívá.

=== Datová vrstva

WARNING: PostgreSQL, FDW a Multicorn...

=== Uživatelské rozhraní

WARNING: REST API, webové rozhraní...


// vim:set spelllang=cs:
