= Správní informační systém: Technická specifikace
:numbered:
:icons: font
:lang: cs
:note-caption: Poznámka
:warning-caption: Pozor
:table-caption: Tabulka
:toc-title: Obsah
:toc: left
:sectnumlevels: 6

== Úvod

Správní informační systém, zkráceně _SpIS_ je otevřený nástroj pro vedení elektronických evidencí. Měl by zpřehlednit výkon organizačních úkonů. V praxi bude tedy evidovat doklady a další dokumenty.

Výběr z funkcí, které očekáváme v prvních verzích:

Hierarchické pracovní struktury::
Rozklad předmětu plnění na jednotlivé dodávané výsledky (což jsou pro nás dokumenty) v předepsané hierarchii (dle typu projektu). Tento postup se jinde označuje pojmem link:https://cs.wikipedia.org/wiki/Work_breakdown_structure[WBS].

Editor dokumentů::
Nástroj pro vytváření a úpravy dokumentů, představující uživatelské rozhraní uzpůsobené jejich konkrétním typům. Využívá zásuvné moduly, které realizují dílčí komponenty rozhraní. Každý typ dokumentu popisuje, jaké komponenty se mají pro jeho pole využít.

Přehledy::
Vhodně zvolené přehledy čerpající z projektů a dalších evidencí. Pro jejich zobrazení se využívají komponenty realizované jako zásuvné moduly. Tyto komponenty se provazují s konkrétními daty, čímž vznikají pohledy, které se dále seskupují do témat.

Oprávnění::
Pružný systém oprávnění založený na uživatelských rolích a organizačních jednotkách umožňuje pracovat pouze s těmi dokumenty a na těch projektech, které se uživatelů týkají.

SpIS bude napojen na vybrané další informační systémy, ze kterých bude čerpat podklady a do kterých bude předávat výstupy nebo dílčí dokumenty. Napojení bude realizováno prostřednictvím datové vrstvy, tedy v databázi.

<<<

=== Sekce a Témata

Za účelem snazší orientaci uživatelů jsou veškeré objekty v systému roztříděny do témat a tématických sekcí. Toto členění nemá žádné důsledky pro funkci, ani pro řízení přístupu. Také nijak nesouvisí s organizačním členěním.

=== Témata

Téma seskupuje pohledy, které mají za úkol poskytnout informace o stavu věcí, se správou projektů a dokumentů, které umožňují tento stav ovlivňovat. Vhodná témata mohou být například *Rozpočet* nebo *Smlouvy*.

Pokud to dává smysl, mohou se věci v tématech opakovat. Například určité pohledy mohou být přínosné pro více témat, některé projekty mohou souviset s vícero tématy a podobně. Názorným příkladem budiž *Nákup*, který zasahuje jak do *Rozpočtu*, tak právě do *Smluv*.

=== Sekce

Sekce slouží k seskupení několika témat. Není běžné, aby se věci opakovaly v různých sekcích, ale není to vyloučeno. Příkladem sekcí mohou být například *Finance*, *Legislativa* a *Vnější ukazatele*. V první sekci se setkáme s tématy, která jsme zmínili výše, v sekci *Legislativa* najdeme jen projekty pro práci s *Vnitřními předpisy* a konečně v sekci *Vnější ukazatele* nenajdeme sice žádné projekty, ale zato se zde setkáme s řadou pohledů na data získaná při provozu instituce, například *Návštěvnost*, nebo *Skladbu uživatelů*.

<<<

== Hierarchické pracovní struktury

Hierarchické pracovní struktury jsou formou vedení *projektů*. Tato forma spočívá v postupném vytváření a schvalování dokumentů, které dokládají provedené úkony. dokumenty mohou být v různých stavech, ale zejména bývají *Rozpracované*, časem *Dokončené* a výjimečně *Provizorní*.

Rozpracované::
Dokumenty, které ještě nejsou hotové a nelze se na ně spoléhat.

Dokončené::
Dokumenty, které jsou hotové a schválené zodpovědnou osobou. Tato osoba ručí za jejich správnost a platnost. Ostatní se na ně mohou obvykle bez obav spolehnout.

Provizorní::
Dokumenty, které jsou hotové, ale nejsou schválené zodpovědnou osobou. Pokud se na ně pracovníci spoléhají, přebírají tím na sebe riziko, které jinak leží na zodpovědné osobě.

Dokumenty ve struktuře na sobě vzájemně závisí. Některé dokumenty tvoří kořeny, na kterých již žádné další dokumenty nezávisí. Na jiných dokumentech závisí jeden i více dokumentů. V podstatě se jedná o acyklický orientovaný graf.

V praxi může hierarchická struktura vypadat například takto (šipky značí závislost):

[plantuml,align="center"]
....
@startuml
rectangle "faktura" <<Faktura>> #9999ff
rectangle "protokol 1" as protokol_1 <<Akceptační protokol>> #99ff99
rectangle "protokol 2" as protokol_2 <<Akceptační protokol>> #ffff99
rectangle "nabídka" <<Nabídka>> #99ff99
rectangle "poptávka" <<Poptávka>> #99ff99
rectangle "specifikace" <<Specifikace>> #99ff99

poptávka -d-> specifikace
faktura -d-> nabídka
faktura -d-> protokol_1
faktura -d-> protokol_2
protokol_1 -d-> specifikace
protokol_1 -d-> nabídka
protokol_2 -d-> specifikace
protokol_2 -d-> nabídka
nabídka -d-> poptávka
@enduml
....

V příkladu je `protokol 2` nedokončený, ale pracovník zodpovědný za schválení faktury ho označil za provizorní. To proto, aby mohl vytvořit provizorní fakturu a mohla proběhnout platba. Pokud se zmýlil a pracovník zodpovědný za `protokol 2` tento nedokončí, mohou být vyvozeny důsledky.

Z důvodu průkaznosti nelze dokončené dokumenty měnit. Pokud by se tak mělo stát, je vytvořen dokument nový, který ten původní nahradí v jeho roli. Pokud se na předchozí dokument jiný dokument spoléhá, je považován za neplatný. Uveďme si příklad:

[plantuml,align="center"]
....
@startuml
rectangle "faktura" <<Faktura>> #ff9999
rectangle "protokol" <<Akceptační protokol>> #9999ff
rectangle "specifikace" <<Specifikace>> #99ff99

faktura -d-> protokol
protokol -d-> specifikace

note right of faktura: verze 1
note right of protokol: verze 2
@enduml
....

V příkladu došlo k tomu, že byla v důsledku aktualizace dokumentu `protokol` zneplatněna aktuální verze dokumentu `faktura`. V této situaci jsou v podstatě jen dvě možnosti jak postupovat správně:

1. Vrátit se k předchozí verzi dokumentu `protokol`, kterou systém uchovává.
2. Schválit novou verzi dokumentu `protokol` a následně vytvořit novou verzi dokumentu `faktura`.

=== Typy projektů

Každý projekt je opatřen popisem své hierarchické struktury. Protože si jsou některé projekty ve své struktuře velmi podobné, definujeme pojmenované typy projektů. Tyto typy reprezentují strukturu, které se dokumenty v projektu přizpůsobují.

V případě potřeby je možné typ aktivního projektu změnit a dokumenty přeuspořádat do nových rolí. Stejně tak je možné do struktury vložit již existující dokumenty, pokud tak nedojde k porušení jejich vazeb na závislosti.

=== Účast na projektech

Po vytvoření projektu lze na základě typů dokumentů přítomných v typu projektu sestavit seznam rolí, které na projektu musejí spolupracovat, aby jej bylo možné dokončit. Účastníci projektu mohou v jakékoliv chvíli pozvat vybrané role (nejen) z tohoto seznamu, čímž dojde k otevření projektu uživatelům v této roli. K účasti na projektu je možné uživatele přizvat i jmenovitě.

Uživatelé přístupem do projektu nezískávají žádná dodatečná oprávnění. Stále mohou manipulovat pouze s dokumenty, ke kterým mají oprávnění vyplývající z uživatelských rolí. V řadě případů je totiž možné do projektu zahrnout libovolné dokumenty, což ovšem nelze produktivně zohlednit pozváním všech uživatelů v organizaci.

Dalším důvodem k individuálnímu pozvání může být například zajištění procesu nákupu napříč útvary, kdy si útvar požadující nákup přizve odborníky z jiného útvaru pro spolupráci na zadání ve společném oboru působnosti. Například tehdy, když si *Oddělení pro styk s veřejností* přizve pracovníky z *Odboru ICT* do projektu v oboru *Technické vybavení pro produkci multimédií*.

<<<

== Dokumenty

Pod pojmem dokument rozumíme strukturovaná strojová data, se kterými uživatel nakládá přímo v systému. Tyto dokumenty často mívají přílohy, což jsou nestrukturovaná data (často různé formátované texty, tabulky či obrázky), které vznikají mimo systém a jsou do něj pouze vkládány.

Dokumenty mají kromě vnitřní struktury také takzvané závislosti a díky nim pak tvoří určité vnější struktury. Tyto závislosti jsou dokumentům vlastní ve všech projektech, kterých jsou součástí.

=== Typy dokumentů

Typy dokumentů shrnují vnitřní strukturu, závislosti, použité komponenty uživatelského rozhraní a další vlastnosti instancí (tedy dokumentů) do jednoznačného pojmenování. V příkladech výše jsme zatím viděli například typy nazvané `Faktura` nebo `Akceptační protokol`.

==== Závislosti

Dokumenty mohou záviset pouze na jiných dokumentech, a to vždy v určitých rolích. Pro ilustraci:

[plantuml,align="center"]
....
@startuml
rectangle "zápůjčka" <<Zápůjčka>> #9999ff
rectangle "předání 1" as předání_1 <<Předávací protokol>> #99ff99
rectangle " " as předání_2 <<Předávací protokol>> #dddddd

zápůjčka -d-> předání_1 : vstupní
zápůjčka -d-> předání_2 : výstupní

note right of zápůjčka
  Rozpracovaný dokument,
  jejž zatím nelze dokončit.
end note

note bottom of předání_2
  Neexistující dokument.
end note
@enduml
....

V příkladu je předávací protokol použit nejprve pro dokumentaci zahájení zápůjčky věci a následně bude použit pro dokumentaci jejího navrácení. Pro vyložení závislého dokumentu `zápůjčka` je podstatné tyto dva protokoly od sebe odlišit.

Oproti instancím (dokumentům) mohou typy záviset pouze na dalších typech (nebo typových třídách, které jsou vysvětleny níže). Pro některé situace může být užitečné, aby dokument závisel na určitém počtu zcela libovolných dokumentů, bez ohledu na jejich typ. To ale odbíháme. Typy pro příklad výše budou vypadat například následovně:

[plantuml,align="center"]
....
@startuml
skinparam monochrome true
skinparam padding 3

rectangle "zápůjčka" <<Zápůjčka>>
rectangle "předání 1" as předání_1 <<Předávací protokol>>
rectangle "předání 2" as předání_2 <<Předávací protokol>>

zápůjčka -d-> "{1,1}" předání_1 : vstupní
zápůjčka -d-> "{1,1}" předání_2 : výstupní
@enduml
....

Za povšimnutí stojí uvedení dokumentů, které by měly být přítomny, ale v příkladu výše zatím schází. Také jsou zde u rolí uvedeny kvantifikátory.

==== Kvantifikace

Závislosti je nutné kvantifikovat. V určité roli může vystupovat konkrétní počet dokumentů. Uveďme si příklad struktury dokumentů:

[plantuml,align="center"]
....
@startuml
rectangle "rozpočet" <<Rozpočet>> #9999ff
rectangle "návrh 1" as návrh_1 <<Dílčí návrh rozpočtu>> #99ff99
rectangle "návrh 2" as návrh_2 <<Dílčí návrh rozpočtu>> #99ff99
rectangle "návrh 3" as návrh_3 <<Dílčí návrh rozpočtu>> #9999ff

rozpočet -d-> návrh_1 : dle návrhu
rozpočet -d-> návrh_2 : dle návrhu
rozpočet -d-> návrh_3 : dle návrhu
@enduml
....

Ve struktuře se vyskytuje trojice dokumentů se shodným typem ve shodné roli. Jak budou vypadat typy pro tuto strukturu? Patrně následovně:

[plantuml,align="center"]
....
@startuml
skinparam monochrome true
skinparam padding 3

rectangle "rozpočet" <<Rozpočet>>
rectangle "návrh" <<Dílčí návrh rozpočtu>>

rozpočet -d-> "{1,}" návrh : dle návrhu
@enduml
....

Kvantifikátor `{1,}` zde značí přítomnost alespoň jednoho dokumentu daného typu v dané roli. Je však možné specifikovat libovolný rozsah, tedy například `{,}` nebo `{0,}` pro libovolný počet dokumentů, `{1,3}` pro jeden až tři dokumenty a `{,5}` nebo `{0,5}` pro až pět dokumentů.

==== Typové třídy

Typové třídy popisují dílčí strukturu dokumentů tak, aby mohlo dojít k použití více typů dokumentů ve stejné roli. Upravují jak strukturu typů dané třídy, tak i jejich závislosti.

Můžeme si například zavést typové třídy `Mající výši plnění (x)` a `Mající termín realizace (x)`, které popisují části schématu dokumentu, ve kterém předepisují přítomnost finanční částky s určitým významem a dále termínu, kdy dojde k nějaké realizaci. S pomocí těchto typových tříd pak můžeme popsat některé závislosti obecněji. Například:

[plantuml,align="center"]
....
@startuml
skinparam monochrome true
skinparam padding 3

rectangle "plán" <<Plán výdajů>>
rectangle "výdaj" <<Pro d, pokud platí\n Mající výši plnění (d),\n Mající termín realizace (d),\n pak libovolné d.>>

plán -d-> "{,}" výdaj : zahrnuje
@enduml
....

Pokud typy dokumentů `Plánovaná investice` a `Plánovaný provozní výdaj` implementují obě tyto typové třídy, pak je možné typy z předešlého případu splnit například následující strukturou:

[plantuml,align="center"]
....
@startuml
rectangle "plán" <<Plán výdajů>> #99ff99
rectangle "výdaj 1" as výdaj_1 <<Plánovaná investice>> #99ff99
rectangle "výdaj 2" as výdaj_2 <<Plánovaný provozní výdaj>> #99ff99

plán -d-> výdaj_1 : zahrnuje
plán -d-> výdaj_2 : zahrnuje
@enduml
....

Termín typová třída se vyskytuje hojně v kontextu funkcionálního programování. Typové třídy tam ale obvykle neposkytují stejný druh polymorfismu jako typové třídy popsané výše. Dle tamější praxe by musely být oba výdaje v příkladu zcela stejného typu.

==== Schéma

Dokument je ve své podstatě stromovou strukturou kompatibilní s formáty JSON, CBOR a YAML.

Každý typ nebo typová třída dokumentu popisuje část schématu. Skutečné schéma získáme sjednocením typu dokumentu se všemi typovými třídami, které typ dokumentu implementuje. Schéma popisuje vnitřní strukturu dokumentu, tedy především názvy a typy jeho polí.

Jazyk schématu vychází z normy link:http://json-schema.org/[JSON Schema], kterou však rozšiřuje o další prvky. Jedná se například o popis uživatelského rozhraní pro editaci stromu, spustitelný kód v řadě významů a také o schopnost přejímat hodnoty ze závislostí.

WARNING: Popsat hlouběji jazyk pro vytváření schémat dokumentů.

=== Komponenty

Komponenty úzce souvisí se schématem dokumentu. Právě z nich si programátor vybírá, jak realizovat uživatelské rozhraní pro úpravy jednotlivých částí dokumentu.

WARNING: Komponenty...

<<<

== Přehledy

=== Pohledy

Pohled může být využit ve více tématech. Každý pohled je určitého typu, což určuje to, jaká data dokáže prezentovat a zároveň způsob, jakým tak činí.

Pokud autor daného typu pohledu vytvořil nástroj pro zobrazení mapových vrstev s vyznačenými body, je možné s jeho pomocí zobrazovat prostorová data. Pokud se jedná o nástroj pro zobrazení tabulky, je možné s jeho pomocí zobrazovat data relační a tak dále.

Obsah pohledu je dán popisem tématu, ve kterém je použit. Součástí tohoto popisu je i soubor dotazů do databáze, prostřednictvím kterých dojde k získání zobrazovaných dat. Tyto dotazy jsou parametrizovány hodnotami, které zvídavý uživatel mění při prohlížení.

<<<

== Model oprávnění

Model oprávnění umožňuje určit, ke kterým datům v systému mají ti kteří uživatelé přístup a mohou je číst nebo měnit. Model pracuje s pravidly ve tvaru *Osoba / Oprávnění / Dokument* a nejlépe jej lze pochopit s pomocí termínů, se kterými pracuje:

Typ dokumentu::
Typ je základní a neměnnou vlastností každého dokumentu, popisující jeho charakter. Dokument může být například typu, který se nazývá *Faktura*.

Obor působnosti::
Právě za účelem kontroly přístupu musí být každý dokument zařazen do takzvaného oboru působnosti. Obor může, ale nemusí vycházet z organizačního členění. Může se tedy jednat například o obor nazvaný *Odbor ICT*.

Předmětný dokument::
Jedná o dokument určitého typu, který spadá do určitého oboru působnosti. Předmětnými dokumenty určitého oprávnění (popsaného níže) mohou být například *Faktury Odboru ICT*.

Způsob manipulace::
Způsobem manipulace rozumíme to, jak bude s předmětnými dokumenty nakládáno. Součástí popisu způsobu je i detailní vymezení toho, jak bude přistupováno k jednotlivým částem předmětných dokumentů. Příkladem způsobu manipulace může být například *Podepisovat*.

Oprávnění::
Spojení způsobu manipulace s typem dokumentů a oborů působnosti. Oprávnění představují to, co uživatelé ke své práci potřebují. Například *Podepisovat Faktury Odboru ICT*.

Role::
Soubor vícero oprávnění se souhrnným názvem. Například role s názvem *Vedoucí ICT* smí *Podepisovat Faktury Odboru ICT* a *Podepisovat Předávací protokoly Oddělení provozu*.

Odvislá role::
Odvislá role je podobná běžné roli, ale vypouští obor působnosti. Ten je doplněn při jmenování. Jako příklad můžeme uvést odvislou roli *Vedoucí (oboru)*, která smí *Podepisovat Faktury (tohoto oboru)*.

Jmenování::
Díky jmenování určité osoby do některé role dojde k aplikaci všech pravidel vyplývajících z dané role na danou osobu a tedy ke vzniku oprávnění osoby nakládat vymezeným způsobem s předmětnými dokumenty.
+
Podobných výsledků můžeme dosáhnout jmenováním do konkrétní role (například *Ondřej Koch* je *Vedoucí ICT*) ale také jmenováním do odvislé role (například *Ondřej Koch* je *Vedoucí (Odboru ICT)*). Druhý způsob se hodí v případech, kdy mají jmenovaní uživatelé k oborům působnosti vždy stejné povinnosti.

=== Uživatelské role

Role představují oprávnění uživatelů, kteří jsou součástí určitých oborů působnosti k manipulaci s množinou předmětných dokumentů, spadajících do stejných nebo jiných oborů.

TIP: Pro jmenování uživatelů do rolí může sloužit zabudovaná funkce systému, nebo k němu může docházet na základě dokumentů, které jsou v systému vedené.

Úlohou rolí je pojmenovat skupiny oprávnění, které mají určití uživatelé a tím umožnit jejich kontrolu a změny. Běžné role se uplatní zejména při netypických situacích, jako jsou projekty mimo běžný rámec organizační struktury. Odvislé role se naopak uplatní při formulování oprávnění pro pravidelné organizační struktury.

=== Způsoby manipulace

Každý dokument se může nacházet ve třech stavech. Manipulace znamená například to, že určitý uživatel u předmětného dokumentu tento stav změní. Tedy dokument rozpracuje, označí za provizorně dokončený, nebo jej dokončí. Obsah dokumentů, které jsou (byť jen provizorně) dokončené, již není možné dále měnit. Provizorní dokument je ovšem možné dokončit.

Některé typy dokumentů mohou pro dokončení vyžadovat podpisy od různých uživatelů. Způsob manipulace pro tyto typy dokumentů určuje, kteří uživatelé jsou oprávněni vytvořit které podpisové doložky.

Způsob manipulace také upravuje, se kterými částmi těla dokumentu a se kterými přílohami přesně smí uživatel nakládat. Oprávnění k částem těl dokumentů jsou rekurzivní a musí tedy podporovat nejen svolení, ale také zákazy.

.Příklad popisu způsobů manipulace s tělem dokumentu
[options="header",cols="5,>2"]
|===
| Cesta              | Manipulace
| `/`                | číst klíče
| `/název`           | číst a měnit hodnotu
| `/zdůvodnění`      | číst a měnit hodnotu
| `/odhadovaná-cena` | číst hodnotu
|===

<<<

== Implementační detaily

=== Architektura

[plantuml,align="center"]
....
@startuml
left to right direction

package "SpIS" {
  () HTTP
  HTTP -u- [Aplikace]

  database "DB"
  () SQL
  [Aplikace] -l-> SQL
  [DB] - SQL

  database "Politiky"
  Politiky -u-> [Aplikace]
}

node "PC" {
  [Prohlížeč] -> HTTP
  [Prohlížeč] .l.> [Pečetidlo]
  [Pečetidlo] -> HTTP
}

actor :Uživatel:

:Uživatel: - [Prohlížeč]
:Uživatel: - [Pečetidlo]

cloud "Externí systémy" {
  [ ] <<ERP a další...>> as Ext1
  [Ext1] -> SQL
}
@enduml
....

Uživatelé budou se SpISem komunikovat pomocí webového rozhraní, spuštěném v běžném webovém prohlížeči. Pro účely elektronického podepisování bude na jejich zařízeních nasazena další aplikace, ve schématu označená jako _Pečetidlo_.

Jak naznačuje schéma výše, _Aplikace_ samotná je běhovým prostředím pro jakési _Politiky_. Ty vytváří programátoři a popisují jimi nejen strukturu dokumentů, které se ve _SpISu_ vyskytují, ale také jejich vzájemné vazby v projektech, použité prvky uživatelského rozhraní a další rysy systému vlastní organizaci, které systém využívá.

=== Datová vrstva

WARNING: PostgreSQL, FDW a Multicorn...

=== Uživatelské rozhraní

WARNING: REST API, webové rozhraní...


// vim:set spelllang=cs:
