= Správní informační systém: Technická specifikace
:numbered:
:icons: font
:lang: cs
:note-caption: Poznámka
:warning-caption: Pozor
:table-caption: Tabulka
:figure-caption: Obrázek
:example-caption: Příklad
:toc-title: Obsah
:toc: left
:toclevels: 3
:sectnumlevels: 6

:y: icon:check[role="green"]
:n: icon:times[role="red"]

== Úvod

Správní informační systém, zkráceně _SpIS_ je otevřený nástroj pro vedení elektronických evidencí. Měl by zpřehlednit výkon organizačních úkonů, mezi které patří například příprava a jednotlivé kroky pro realizaci veřejných zakázek včetně dodání podkladů pro fakturaci, plánování rozpočtu a jednotlivých výdajových záměrů nebo nastavení pracovních procesů a schvalovacích mechanismů dle rolí přidělených pracovníkům a dodavatelům dané organizace. Systém bude tedy v praxi evidovat doklady a další dokumenty.

Výběr z funkcí, které očekáváme v prvních verzích:

Hierarchické pracovní struktury::
Rozklad předmětu plnění na jednotlivé dodávané výsledky (což jsou pro nás dokumenty) v předepsané hierarchii (dle typu projektu). Tento postup se jinde označuje pojmem link:https://cs.wikipedia.org/wiki/Work_breakdown_structure[WBS].

Editor dokumentů::
Nástroj pro vytváření a úpravy dokumentů, představující uživatelské rozhraní uzpůsobené jejich konkrétním typům. Využívá zásuvné moduly, které realizují dílčí komponenty rozhraní. Každý typ dokumentu popisuje, jaké komponenty se mají pro jeho pole využít.

Přehledy::
Vhodně zvolené přehledy čerpající z projektů a dalších evidencí. Pro jejich zobrazení se využívají komponenty realizované jako zásuvné moduly. Tyto komponenty se provazují s konkrétními daty, čímž vznikají pohledy, které se dále seskupují do témat.

Oprávnění::
Pružný systém oprávnění založený na uživatelských rolích a organizačních jednotkách umožňuje pracovat pouze s těmi dokumenty a na těch projektech, které se uživatelů týkají.

SpIS bude napojen na vybrané další informační systémy, ze kterých bude čerpat podklady a do kterých bude předávat výstupy nebo dílčí dokumenty. Napojení bude realizováno prostřednictvím datové vrstvy, tedy v databázi.

<<<

== Struktura uživatelského rozhraní

=== Sekce

Za účelem snazší orientaci uživatelů jsou veškeré objekty v systému roztříděny do témat a tématických sekcí. Toto členění nemá žádné důsledky pro funkci, ani pro řízení přístupu. Také nijak nesouvisí s organizačním členěním.

Sekce slouží k seskupení několika témat. Není běžné, aby se věci opakovaly v různých sekcích, ale není to vyloučeno. Příkladem sekcí mohou být například *Finance*, *Legislativa* a *Vnější ukazatele*. V první sekci se setkáme s tématy, která jsme zmínili výše, v sekci *Legislativa* najdeme jen projekty pro práci s *Vnitřními předpisy* a konečně v sekci *Vnější ukazatele* nenajdeme sice žádné projekty, ale zato se zde setkáme s řadou pohledů na data získaná při provozu instituce, například *Návštěvnost*, nebo *Skladbu uživatelů*.

==== Témata

Téma seskupuje pohledy a sestavy, které mají za úkol poskytnout informace o stavu věcí, se správou projektů a dokumentů, které umožňují tento stav ovlivňovat. Vhodná témata mohou být například *Rozpočet* nebo *Smlouvy*.

Pokud to dává smysl, mohou se věci v tématech opakovat. Například určité pohledy mohou být přínosné pro více témat, některé projekty mohou souviset s vícero tématy a podobně. Názorným příkladem budiž *Nákup*, který zasahuje jak do *Rozpočtu*, tak právě do *Smluv*.

===== Pohledy

Pohledům je v rámci daného tématu věnován hlavní prostor. Některé pohledy jsou interaktivní, takže je možné s nimi manipulovat a dovídat se tak nové souvislosti. Například pokud pohled zobrazuje mapu, je možné s ní pohybovat, přibližovat ji nebo ji oddalovat. Pokud jsou na mapě interaktivní objekty, je možné je aktivovat a zkoumat jejich detaily.

Některé pohledy mohou umožňovat přímo spustit nový projekt, nebo se odkazovat na existující projekty a dokumenty. Tyto vazby bývají obvykle realizovány odkazy, které může uživatel otevřít v nové záložce prohlížeče.

===== Sestavy

Na stránce každého tématu je vyhrazen prostor, ve kterém se nachází odkazy jednak na systémové a dále také na daným uživatelem vytvořené sestavy pohledů. Protože pohledy podporují zobrazení verze pro tisk, je možné sestavy s automatickým skrytím nepotřebných prvků uživatelského rozhraní tisknout běžným způsobem.

Ze stránky tématu je možné aktivovat editor sestav, který umožňuje na stránku uspořádat výběr z pohledů, ke kterým má uživatel přístup. Těmto pohledům je následně možné interaktivně nastavit potřebné zobrazení. Takto připravenou sestavu je následně možné uložit, nebo případně jen vytisknout.

===== Projekty

Pokud téma obsahuje alespoň jeden typ projektu, je na jeho stránce k dispozici přehled projektů, kterých se aktuální uživatel účastní spolu s prvkem, který umožňuje zahájit nový, je-li k tomu uživatel oprávněn.

Z přehledu jsou patrné základní údaje o projektech a zda-li do nich může uživatel zasáhnout, případně je-li to po něm někým požadováno. Přehled je interaktivní a umožňuje třídění i hledání.

===== Dokumenty

Pokud téma obsahuje prostřednictvím přiřazených typů projektů alespoň jeden typ dokumentu, je na jeho stránce k dispozici přehled dokumentů, ke kterým má aktuální uživatel přístup. Pokud je k tomu uživatel oprávněn, může z tohoto přehledu zahájit změnu dokumentu.

Z přehledu jsou patrné základní údaje o dokumentech. Dá se z něj také zjistit, do kterých projektů vstupují, má-li k nim aktuální uživatel přístup. Přehled je interaktivní a umožňuje třídění i hledání.

=== Předvolby uživatele

Část systému umožňující uživateli přizpůsobit si systém dle svých potřeb. Uživatel si zde může zvolit alespoň jazyk uživatelského rozhraní a způsob upozorňování na události v systému.

.Předvolby upozorňování
[options="header",cols="<4,^1,^1,^1"]
|===
| Událost                                           | Nikdy | Ihned | Souhrnně
| Je požadována Vaše práce na dokumentu             |       | {y}   | {y}
| Můžete vytvořit chybějící dokument                | {y}   |       | {y}
| Vámi naposledy upravený dokument byl změněn       | {y}   | {y}   | {y}
| Vámi sledovaný dokument byl změněn                | {y}   | {y}   | {y}
| Dokument projektu, které se účastníte, byl změněn | {y}   | {y}   | {y}
| Projekt, kterého se účastníte byl změněn          | {y}   | {y}   | {y}
| Změnila se Vaše účast na projektu                 | {y}   | {y}   | {y}
| Změnily se Vaše role v systému                    | {y}   | {y}   | {y}
|===

=== Předvolby systému

Část systému umožňující správci nastavit jednak výchozí uživatelské předvolby, ale také případná obecná nastavení.

==== Integrační můstky

Za účelem alespoň částečného řízení komunikaci s navázanými cizími systémy je zde možné nastavovat a měnit předvolby ve tvaru `klíč = hodnota`, které mohou můstky pro integraci s cizími systémy následně využít.

Pokud by existoval můstek pro komunikaci s veřejnými rejstříky, volbou `ares.refresh_after = 48` bychom mu mohli sdělit, že má záznamy převzaté ze systému ARES kontrolovat nejdříve po 48 hodinách.

Podrobnější konfiguraci budou muset integrační můstky implementovat odděleně.

==== Správa modelu oprávnění

Součástí předvoleb systému je pak správa modelu oprávnění, v rámci které je možné například nastavit párování skupin či rolí z evidence uživatelů s rolemi systému nebo upravit rozsah oprávnění jednotlivých rolí.

Více o modelu najdete v kapitole <<Model oprávnění>>.

<<<

== Pohledy, komponenty a zdroje dat

Každý pohled využívá pro zobrazení určitou komponentu. Pokud je komponenta určena pro zobrazení mapových vrstev s vyznačenými body, je možné ji použít pro zobrazení prostorových dat. Pokud se jedná o komponentu pro zobrazení tabulky, je možné pomoci ní zobrazovat data relační a tak dále.

To, jaká data pohled představuje, je kromě komponenty dáno zejména souborem datových zdrojů, ze kterých pohled čerpá. Tyto zdroje mohou být při použití interaktivních komponent ovlivněny hodnotami, které uživatel při prohlížení mění.

.Popis pohledu
====
[source,yaml]
....
# Název pohledu včetně české lokalizace
name: Event Calendar
name[cs]: Kalendář akcí

# Výběr komponenty uživatelského rozhraní
interface:
  component: CalendarView

  # Úprava konfigurace komponenty
  options:
    mode: next-30-days

# Výběr datových zdrojů pro komponentu
data:
  holidays: planning.czech_holidays
  events: planning.events
....
====

Komponentu tvoří popis jejího rozhraní, včetně popisu zdrojů dat, ze kterých dokáže čerpat a dále kód pro její zobrazení. Komponenta je totiž v pohledu navázána na sadu datových zdrojů, což jsou fakticky procedury uložené v databázi. Popis rozhraní komponenty umožňuje provést automatickou kontrolu shody s rozhraním procedur.

Vzhledem k tomu, že formátem pro komunikaci komponent s datovými zdroji je `JSON`, je možné s výhodou opět vyžít připravované normy link:http://json-schema.org/[JSON Schema].

.Popis komponenty
====
[source,yaml]
....
name: Calendar
name[cs]: Kalendář

# Popis očekávaných datových zdrojů
sources:
  holidays:
    name: Holidays
    name[cs]: Svátky

    # Komponenta bude fungovat i bez tohoto zdroje
    optional: true

    # Schéma poskytovaných dat
    provides: {$ref: "calendar.yaml#/definitions/events"}

    # Schémata očekávaných argumentů
    expects:
      period: {$ref: "calendar.yaml#/definitions/period"}

  events:
    name: Events
    name[cs]: Události

    provides: {$ref: "calendar.yaml#/definitions/events"}
    expects:
      period: {$ref: "calendar.yaml#/definitions/period"}

# Popis dalších nastavení
options:
  mode: {$ref: "calendar.yaml#/definitions/mode"}
....
====

Pro kontrolu datového zdroje je v příkladu níže popsána uložená procedura `calendar.events`.

.Popis uložené procedury
====
[source,yaml]
....
name: Calendar Events
name[cs]: Kalendářní události

# Plně kvalifikovaný název uložené procedury
procedure: calendar.events

provides: {$ref: "calendar.yaml#/definitions/events"}
expects:
  period: {$ref: "calendar.yaml#/definitions/period"}
....
====

<<<

== Hierarchické pracovní struktury

Hierarchické pracovní struktury jsou formou vedení *projektů*. Tato forma spočívá v postupném vytváření a schvalování dokumentů, které dokládají provedené úkony. Dokumenty mohou být v různých stavech, ale zejména bývají *Rozpracované*, časem *Dokončené* a výjimečně *Provizorní*.

Rozpracované::
Dokumenty, které ještě nejsou hotové a nelze se na ně spoléhat.

Dokončené::
Dokumenty, které jsou hotové a schválené zodpovědnou osobou. Tato osoba ručí za jejich správnost a platnost. Ostatní se na ně mohou obvykle bez obav spolehnout.

Provizorní::
Dokumenty, které jsou hotové, ale nejsou schválené zodpovědnou osobou. Pokud se na ně pracovníci spoléhají, přebírají tím na sebe riziko, které jinak leží na zodpovědné osobě.

Dokumenty ve struktuře na sobě vzájemně závisí a tvoří tak acyklický orientovaný graf.

.Hierarchická pracovní struktura (šipky značí závislost)
====
[plantuml,align="center"]
....
@startuml
rectangle "faktura" <<Faktura>> #9999ff
rectangle "protokol 1" as protokol_1 <<Akceptační protokol>> #99ff99
rectangle "protokol 2" as protokol_2 <<Akceptační protokol>> #ffff99
rectangle "nabídka" <<Nabídka>> #99ff99
rectangle "poptávka" <<Poptávka>> #99ff99
rectangle "specifikace" <<Specifikace>> #99ff99

poptávka -d-> specifikace
faktura -d-> nabídka
faktura -d-> protokol_1
faktura -d-> protokol_2
protokol_1 -d-> specifikace
protokol_1 -d-> nabídka
protokol_2 -d-> specifikace
protokol_2 -d-> nabídka
nabídka -d-> poptávka
@enduml
....
====

V příkladu je `protokol 2` nedokončený, ale pracovník zodpovědný za schválení faktury ho označil za provizorní. To proto, aby mohl vytvořit provizorní fakturu a mohla proběhnout platba. Pokud se zmýlil a pracovník zodpovědný za `protokol 2` tento nedokončí, mohou být vyvozeny důsledky.

Z důvodu průkaznosti nelze dokončené dokumenty měnit. Pokud by se tak mělo stát, je vytvořen dokument nový, který ten původní nahradí v jeho roli. Pokud se na předchozí dokument jiný dokument spoléhá, je považován za neplatný.

.Zneplatnění dokumentu revizí jeho závislosti
====
[plantuml,align="center"]
....
@startuml
rectangle "faktura" <<Faktura>> #ff9999
rectangle "protokol" <<Akceptační protokol>> #9999ff
rectangle "specifikace" <<Specifikace>> #99ff99

faktura -d-> protokol
protokol -d-> specifikace

note right of faktura: verze 1
note right of protokol: verze 2
@enduml
....
====

V příkladu došlo k tomu, že byla v důsledku aktualizace dokumentu `protokol` zneplatněna aktuální verze dokumentu `faktura`. V této situaci jsou v podstatě jen dvě možnosti jak postupovat správně:

1. Vrátit se k předchozí verzi dokumentu `protokol`, kterou systém uchovává.
2. Schválit novou verzi dokumentu `protokol` a následně vytvořit novou verzi dokumentu `faktura`.

=== Typy projektů

Každý projekt je opatřen popisem své hierarchické struktury. Protože si jsou některé projekty ve své struktuře velmi podobné, definujeme pojmenované typy projektů. Tyto typy reprezentují strukturu, které se dokumenty v projektu přizpůsobují.

V případě potřeby je možné typ aktivního projektu změnit a dokumenty přeuspořádat do nových rolí. Stejně tak je možné do struktury vložit již existující dokumenty, pokud tak nedojde k porušení jejich vazeb na závislosti.

=== Účast na projektech

Po vytvoření projektu lze na základě typů dokumentů přítomných v typu projektu sestavit seznam rolí, které na projektu musejí spolupracovat, aby jej bylo možné dokončit. Účastníci projektu mohou v jakékoliv chvíli pozvat vybrané role (nejen) z tohoto seznamu, čímž dojde k otevření projektu uživatelům v této roli. K účasti na projektu je možné uživatele přizvat i jmenovitě.

Uživatelé přístupem do projektu nezískávají žádná dodatečná oprávnění. Stále mohou manipulovat pouze s dokumenty, ke kterým mají oprávnění vyplývající z uživatelských rolí. V řadě případů je totiž možné do projektu zahrnout libovolné dokumenty, což ovšem nelze produktivně zohlednit pozváním všech uživatelů v organizaci.

Dalším důvodem k individuálnímu pozvání může být například zajištění procesu nákupu napříč útvary, kdy si útvar požadující nákup přizve odborníky z jiného útvaru pro spolupráci na zadání ve společném oboru působnosti. Například tehdy, když si *Oddělení pro styk s veřejností* přizve pracovníky z *Odboru ICT* do projektu v oboru *Technické vybavení pro produkci multimédií*.

<<<

== Dokumenty

Pod pojmem dokument rozumíme strukturovaná strojová data, se kterými uživatel nakládá přímo v systému. Tyto dokumenty často mívají přílohy, což jsou nestrukturovaná data (často různé formátované texty, tabulky či obrázky), které vznikají mimo systém a jsou do něj pouze vkládány.

Dokumenty mají kromě vnitřní struktury také takzvané závislosti a díky nim pak tvoří určité vnější struktury. Tyto závislosti jsou dokumentům vlastní ve všech projektech, kterých jsou součástí.

=== Typy dokumentů

Typy dokumentů shrnují vnitřní strukturu, závislosti, použité komponenty uživatelského rozhraní a další vlastnosti instancí (tedy dokumentů) do jednoznačného pojmenování. V příkladech výše jsme zatím viděli například typy nazvané `Faktura` nebo `Akceptační protokol`.

==== Závislosti

Dokumenty mohou záviset pouze na jiných dokumentech, a to vždy v určitých rolích.

.Závislosti mají konkrétní role
====
[plantuml,align="center"]
....
@startuml
rectangle "zápůjčka" <<Zápůjčka>> #9999ff
rectangle "předání 1" as předání_1 <<Předávací protokol>> #99ff99
rectangle " " as předání_2 <<Předávací protokol>> #dddddd

zápůjčka -d-> předání_1 : vstupní
zápůjčka -d-> předání_2 : výstupní

note right of zápůjčka
  Rozpracovaný dokument,
  jejž zatím nelze dokončit.
end note

note bottom of předání_2
  Neexistující dokument.
end note
@enduml
....
====

V příkladu je předávací protokol použit nejprve pro dokumentaci zahájení zápůjčky věci a následně bude použit pro dokumentaci jejího navrácení. Pro vyložení závislého dokumentu `zápůjčka` je podstatné tyto dva protokoly od sebe odlišit.

Oproti instancím (dokumentům) mohou typy záviset pouze na dalších typech (nebo typových třídách, které jsou vysvětleny níže). Pro některé situace může být užitečné, aby dokument závisel na určitém počtu zcela libovolných dokumentů, bez ohledu na jejich typ. To ale odbíháme.

.Typy pro předchozí příklad
====
[plantuml,align="center"]
....
@startuml
skinparam monochrome true
skinparam padding 3

rectangle "zápůjčka" <<Zápůjčka>>
rectangle "předání 1" as předání_1 <<Předávací protokol>>
rectangle "předání 2" as předání_2 <<Předávací protokol>>

zápůjčka -d-> "{1,1}" předání_1 : vstupní
zápůjčka -d-> "{1,1}" předání_2 : výstupní
@enduml
....
====

Za povšimnutí stojí uvedení dokumentů, které by měly být přítomny, ale v příkladu výše zatím schází. Také jsou zde u rolí uvedeny kvantifikátory.

==== Kvantifikace

Závislosti je nutné kvantifikovat. V určité roli může vystupovat konkrétní počet dokumentů.

.Struktura se třemi dokumenty ve stejné roli
====
[plantuml,align="center"]
....
@startuml
rectangle "rozpočet" <<Rozpočet>> #9999ff
rectangle "návrh 1" as návrh_1 <<Dílčí návrh rozpočtu>> #99ff99
rectangle "návrh 2" as návrh_2 <<Dílčí návrh rozpočtu>> #99ff99
rectangle "návrh 3" as návrh_3 <<Dílčí návrh rozpočtu>> #9999ff

rozpočet -d-> návrh_1 : dle návrhu
rozpočet -d-> návrh_2 : dle návrhu
rozpočet -d-> návrh_3 : dle návrhu
@enduml
....
====

Jak budou vypadat typy pro tuto strukturu?

.Typy pro předchozí příklad
====
[plantuml,align="center"]
....
@startuml
skinparam monochrome true
skinparam padding 3

rectangle "rozpočet" <<Rozpočet>>
rectangle "návrh" <<Dílčí návrh rozpočtu>>

rozpočet -d-> "{1,}" návrh : dle návrhu
@enduml
....
====

Kvantifikátor `{1,}` zde značí přítomnost alespoň jednoho dokumentu daného typu v dané roli. Je však možné specifikovat libovolný rozsah, tedy například `{,}` nebo `{0,}` pro libovolný počet dokumentů, `{1,3}` pro jeden až tři dokumenty a `{,5}` nebo `{0,5}` pro až pět dokumentů.

==== Typové třídy

Typové třídy popisují dílčí strukturu dokumentů tak, aby mohlo dojít k použití více typů dokumentů ve stejné roli. Upravují jak strukturu typů dané třídy, tak i jejich závislosti.

Můžeme si například zavést typové třídy `Mající výši plnění (x)` a `Mající termín realizace (x)`, které popisují části schématu dokumentu, ve kterém předepisují přítomnost finanční částky s určitým významem a dále termínu, kdy dojde k nějaké realizaci. S pomocí těchto typových tříd pak můžeme popsat některé závislosti obecněji.

.Využití typové třídy
====
[plantuml,align="center"]
....
@startuml
skinparam monochrome true
skinparam padding 3

rectangle "plán" <<Plán výdajů>>
rectangle "výdaj" <<Pro d, pokud platí\n Mající výši plnění (d),\n Mající termín realizace (d),\n pak libovolné d.>>

plán -d-> "{,}" výdaj : zahrnuje
@enduml
....
====

Pokud typy dokumentů `Plánovaná investice` a `Plánovaný provozní výdaj` implementují obě tyto typové třídy, pak je možné typy z předešlého případu splnit například následující strukturou.

.Implementace typů z předchozího příkladu
====
[plantuml,align="center"]
....
@startuml
rectangle "plán" <<Plán výdajů>> #99ff99
rectangle "výdaj 1" as výdaj_1 <<Plánovaná investice>> #99ff99
rectangle "výdaj 2" as výdaj_2 <<Plánovaný provozní výdaj>> #99ff99

plán -d-> výdaj_1 : zahrnuje
plán -d-> výdaj_2 : zahrnuje
@enduml
....
====

Termín typová třída se vyskytuje hojně v kontextu funkcionálního programování. Typové třídy tam ale obvykle neposkytují stejný druh polymorfismu jako typové třídy popsané výše. Dle tamější praxe by musely být oba výdaje v příkladu zcela stejného typu.

==== Schéma

Dokument je ve své podstatě stromovou strukturou kompatibilní s formáty JSON, CBOR a YAML.

Každý typ nebo typová třída dokumentu popisuje část schématu. Skutečné schéma získáme sjednocením typu dokumentu se všemi typovými třídami, které typ dokumentu implementuje. Schéma popisuje vnitřní strukturu dokumentu, tedy především názvy a typy jeho polí.

Jazyk schématu vychází z připravované normy link:http://json-schema.org/[JSON Schema], kterou však rozšiřuje o další prvky. Jedná se například o popis uživatelského rozhraní pro editaci stromu, spustitelný kód v řadě významů a také o schopnost přejímat hodnoty ze závislostí.

[source,yaml]
.{example-caption} {counter:example}. Schéma zápůjčky (hlavička)
....
name: Lease
name[cs]: Zápůjčka

dependencies:
  lender:
    name: Lender
    name[cs]: Půjčovatel
    type: Party

  borrower:
    name: Borrower
    name[cs]: Vypůjčovatel
    type: Party

attachments:
  subject:
    name: Subject
    name[cs]: Předmět
    accept: [document, image]
    count: [0, inf]
....

V příkladu výše vidíme závislosti (`lender` a `borrower`), které dokument vyžaduje. Protože u nich není uvedena žádná kvantifikace, předpokládá se výchozí, tedy `{1,1}`. Typ obou závislostí je `Party` (smluvní strana), což bude pravděpodobně typová třída.

Dále můžeme vidět jediný typ přílohy, dokument nebo obrázek v roli `subject` (předmět). Vzhledem k neomezenému počtu se bude patrně jednat o sbírku dokladů popisujících zapůjčovanou věc a snad i další podmínky zápůjčky.

Následuje popis těla dokumentu.

[source,yaml]
.{example-caption} {counter:example}. Schéma zápůjčky (tělo dokumentu)
....
import:
  - from: spis.datetime
    names: [today, timedelta]

body:
  type: object
  required: [period]

  properties:
    period:
      allOf: [{$ref: "calendar.yaml#/definitions/daterange"}]

      interface:
        component: DateRangePicker

        data:
          holidays: planning.czech_holidays

        options:
          mode: year-view

      default:
        start: !eval "today()"
        end: !eval "today() + timedelta(days=14)"
....

Hned v první části příkladu vidíme import funkcí (`today` a `timedelta` z modulu `spis.datetime`). V politice je možné využívat vypočítaných hodnot a tímto způsobem je možné získat knihovní funkce. Modul `spis` a jeho součásti obsahují zabudované funkce systému.

V popisu samotného těla dokumentu vidíme, že se v tomto případě nejedná o žádnou složitou strukturu, ale pouze o doplnění příloh a závislostí o termín platnosti výpůjčky představovaný sekcí `period`. Její hrubý popis je čerpán z knihovny schémat a úpravy probíhají pomocí komponenty editoru dokumentů `DateRangePicker` se zobrazením svátků.

V závěru sekce pak nalezneme určení výchozích hodnot pro nový dokument, které využívá právě knihovních funkcí importovaných výše k nastavení výpůjčky ode dnes na 14 dní.

=== Komponenty

Komponenty úzce souvisí se schématem dokumentu. Právě v něm si programátor vybírá, ze kterých se prostředí pro úpravy daného typu dokumentu bude skládat.

Ve většině případů pracují komponenty se skaláry a jedná se v podstatě o dobře známé prvky uživatelských rozhraní. V jistých případech však komponenty editoru dokumentů vyžadují další informace a začínají ve svém uspořádání připomínat komponenty pohledů.

[source,yaml]
.{example-caption} {counter:example}. Popis komponenty umožňující výběr dne
....
name: Simple Date Picker
name[cs]: Jednoduchý výběr dne

provides: {$ref: "calendar.yaml#/definitions/date"}

sources:
  holidays:
    name: Holidays
    name[cs]: Svátky

    optional: true
    provides: {$ref: "calendar.yaml#/definitions/events"}
    expects:
      period: {$ref: "calendar.yaml#/definitions/period"}

options:
  mode: {$ref: "calendar.yaml#/definitions/mode"}
....

Z příkladu výše je patrná hlavní odlišnost popisu komponenty editoru dokumentů od popisu komponenty pohledu. Jedná se o klíč `provides`, který popisuje schéma dílčí části dokumentu, jejíž úpravy komponenta zprostředkovává.

=== Verze a revize

Ačkoliv se může zdát, že dokumenty lze upravovat, ve skutečnosti tomu tak není. Při každé zdánlivé změně vzniká nová revize dokumentu, která předchozí revizi nahrazuje. Souběžně s označením revize je u každého dokumentu vedeno také označení jeho verze.

Při každém dokončení dokumentu dochází k uzamčení jeho současné verze na současné revizi. To znamená, že již není možné vytvořit revizi se shodnou verzí a musí tedy při další změně dojít k použití nového označení.

.Změny ve verzi a revizi v důsledku úprav dokumentu
[options="header",cols="^1,^1,<5"]
|===
| Verze | Revize | Popis změny
|   1   |   1    | Dokument vytvořen
|   1   |   2    | Drobná změna dokumentu
|   1   |   3    | Zásadní změna dokumentu
|   1   |   4    | Dokument dokončen
|   2   |   5    | Drobná změna dokumentu
|   2   |   6    | Dokument zrušen
|===

Běžný postup úpravy dokumentu probíhá tak, že si uživatel otevře aktuální revizi, zanese do ní požadované změny a výsledek uloží jako revizi novou. Pokud dojde k souběhu a druhý uživatel (například v době kdy první stále chystá své změny) úspěšně vytvoří novou revizi, dojde při pokusu o uložení ze strany prvního uživatele ke konfliktu.

Konflikt je uživateli prezentován v plné šíři. Pokud chce se změnami pokračovat, musí se u každé komponenty rozhodnout pro některou z následujících možností:

1. Přijme změnu od konkurujícího uživatele.
2. Zamítne změnu a navrátí hodnotu do původního stavu.
3. Prosadí svou změnu, kterou případně dále přizpůsobí.

Po vypořádání všech konfliktů je uživateli opět umožněno uložit novou revizi dokumentu.

<<<

== Model oprávnění

Model oprávnění umožňuje určit, ke kterým datům v systému mají jací uživatelé přístup a mohou je číst nebo měnit. Model pracuje s pravidly ve tvaru *Osoba / Oprávnění / Dokument* a nejlépe jej lze pochopit s pomocí termínů, se kterými pracuje:

Typ dokumentu::
Typ je základní a neměnnou vlastností každého dokumentu popisující jeho charakter. Dokument může být například typu *Faktura*.

Obor působnosti::
Právě za účelem kontroly přístupu musí být každý dokument zařazen do takzvaného oboru působnosti. Obor může, ale nemusí vycházet z organizačního členění. Může se tedy jednat například o obor nazvaný *Odbor ICT*.

Předmětný dokument::
Jedná se o dokument určitého typu, který spadá do určitého oboru působnosti. Předmětnými dokumenty určitého oprávnění (popsaného níže) mohou být například *Faktury Odboru ICT*.

Způsob manipulace::
Způsobem manipulace rozumíme to, jak bude s předmětnými dokumenty nakládáno. Součástí popisu způsobu je i detailní vymezení toho, jak bude přistupováno k jednotlivým částem předmětných dokumentů. Příkladem způsobu manipulace může být například *Podepisovat*.

Oprávnění::
Spojení způsobu manipulace s typem dokumentů a oborů působnosti. Oprávnění představují to, co uživatelé ke své práci potřebují. Například *Podepisovat Faktury Odboru ICT*.

Role::
Soubor vícero oprávnění se souhrnným názvem. Například role s názvem *Vedoucí ICT* smí *Podepisovat Faktury Odboru ICT* a *Podepisovat Předávací protokoly Oddělení provozu*.

Odvislá role::
Odvislá role je podobná běžné roli, ale vypouští obor působnosti. Ten je doplněn při jmenování. Jako příklad můžeme uvést odvislou roli *Vedoucí (oboru)*, která smí *Podepisovat Faktury (tohoto oboru)*.

Jmenování::
Díky jmenování určité osoby do některé role dojde k aplikaci všech pravidel vyplývajících z dané role na danou osobu a tedy ke vzniku oprávnění osoby nakládat vymezeným způsobem s předmětnými dokumenty.
+
Podobných výsledků můžeme dosáhnout jmenováním do konkrétní role (například *Ondřej Koch* je *Vedoucí ICT*), ale také jmenováním do odvislé role (například *Ondřej Koch* je *Vedoucí (Odboru ICT)*). Druhý způsob se hodí v případech, kdy mají jmenovaní uživatelé k oborům působnosti vždy stejné povinnosti.

=== Uživatelské role

Role představují oprávnění uživatelů, kteří jsou součástí určitých oborů působnosti k manipulaci s množinou předmětných dokumentů spadajících do stejných nebo jiných oborů.

TIP: Pro jmenování uživatelů do rolí může sloužit například jejich příslušnost do určitých skupin, která se zjistí z vnější evidence uživatelů.

Úlohou rolí je pojmenovat skupiny oprávnění, které mají určití uživatelé, a tím umožnit jejich kontrolu a změny. Běžné role se uplatní zejména při netypických situacích, jako jsou projekty mimo běžný rámec organizační struktury. Odvislé role se naopak uplatní při formulování oprávnění pro pravidelné organizační struktury.

=== Způsoby manipulace

Každý dokument se může nacházet ve třech stavech. Manipulace znamená například to, že určitý uživatel u předmětného dokumentu tento stav změní. Tedy dokument rozpracuje, označí za provizorně dokončený nebo jej dokončí. Obsah dokumentů, které jsou (byť jen provizorně) dokončené, již není možné dále měnit. Provizorní dokument však dokončit lze.

Některé typy dokumentů mohou pro dokončení vyžadovat podpisy od různých uživatelů. Způsob manipulace pro tyto typy dokumentů určuje, kteří uživatelé jsou oprávněni vytvořit které podpisové doložky.

Způsob manipulace také upravuje, se kterými částmi těla dokumentu a se kterými přílohami přesně smí uživatel nakládat. Oprávnění k částem těl dokumentů jsou rekurzivní a musí tedy podporovat nejen svolení, ale také zákazy.

.Popis způsobů manipulace s tělem dokumentu
[options="header",cols="5,>2"]
|===
| Cesta              | Manipulace
| `/`                | číst klíče
| `/název`           | číst a měnit hodnotu
| `/zdůvodnění`      | číst a měnit hodnotu
| `/odhadovaná-cena` | číst hodnotu
|===

<<<

== Implementační detaily

=== Architektura

[plantuml,align="center"]
....
@startuml
left to right direction

package "SpIS" {
  component Aplikace
  database Data
  database Politiky
  () HTTP
  () SQL

  HTTP -- Aplikace
  Aplikace -d-> SQL
  Politiky .r.> Aplikace
  SQL -l- Data
}

node "PC" {
  component Prohlížeč
  component Pečetidlo

  Prohlížeč -> HTTP
  Prohlížeč .l.> Pečetidlo
  Pečetidlo -> HTTP
}

actor :Uživatel:

:Uživatel: - Prohlížeč
:Uživatel: - Pečetidlo
@enduml
....

Uživatelé budou se SpISem komunikovat pomocí webového rozhraní spuštěném v běžném webovém prohlížeči. Pro účely elektronického podepisování bude na jejich zařízeních nasazena další aplikace, ve schématu označená jako _Pečetidlo_.

Jak naznačuje schéma výše, _Aplikace_ samotná je běhovým prostředím pro určité _Politiky_. Ty vytváří programátoři a popisují jimi nejen strukturu dokumentů, které se ve SpISu vyskytují, ale také jejich vzájemné vazby v projektech, použité prvky uživatelského rozhraní a další rysy systému dané organizace.

=== Datová vrstva

==== PostgreSQL

Úlohu hlavního databázového systému plní otevřené řešení _PostgreSQL_. Protože by tento požadavek mohl být zastánci uzavřených databázových systémů vnímán jako sporný, uvedu důležité vlastnosti, které z něj činí nejlepší nástroj pro tento účel:

* Kvalitně zpracovaná soustava spouští (triggers), která umožňuje reagovat na změny v datech, zajišťovat jejich soudržnost a dále je přenášet a měnit.

* Schopnost plnohodnotně pracovat s volně uspořádanými daty ve formátu JSON, ve kterém jsou ukládány dokumenty. Změny v nich je pak pomocí spouští možné šířit i do dalších tabulek přímo uvnitř databáze.

* Vestavěný nástroj pro upozornění posluchačů na události, ke kterým v databázi dochází. Zejména užitečný společně se spouštěmi, protože umožňuje například okamžitě uvědomit různé synchronizační nástroje nebo dokonce uživatelské rozhraní o změnách, na které je nutné reagovat.

* Lze doplnit o nástroj pro vytváření pohledů na cizí data, tedy data z jiných informačních systémů nebo databází bez nutnosti je přenášet dopředu. Je možné se takto například pomocí protokolu LDAP napojit na evidenci uživatelů v systému Microsoft Active Directory.


==== Dokumenty

Ústřední skupinou objektů v databázi jsou dokumenty. Tyto dokumenty, vyjádřené hodnotou typu `jsonb` (binární JSON) jsou doplněny o řadu metadat v rozsahu vyplývajícím z ostatních požadavků. Dokumenty všech typů budou uloženy v jediné tabulce a bude u nich při ukládání docházet alespoň k základní kontrole dle schématu odpovídajícímu jejich typu.

Obsah dokumentů by nemělo být vůbec možné měnit, pouze vytvářet nové revize a upravovat jejich stav směrem k dokončení a podepsání.

==== Zdroje dat

Relační datové struktury, ze kterých uložené procedury čerpají data pro pohledy, se mohou do systému dostat dvěma způsoby. Může jít o data z jiných systémů nebo rozbory dokumentů.

===== Data z cizích systémů

Data z cizích systémů se do systému zanáší zpravidla pomocí zvláštních nástrojů vyvinutých na míru jednak cizímu systému a dále dle potřeb konkrétních procesů vedených ve SpISu.

[plantuml,align="center"]
....
@startuml
package "SpIS" {
  database "DB" as db1
  () SQL as sql1
  db1 - sql1
}

package "Cizí systém" {
  component "Aplikace" as app2
  () API as api2
  api2 - app2
}

component "Nástroj pro\n synchronizaci" as sn

sn <-u-> api2
sn <-u-> sql1
@enduml
....

V některých případech je možné využít také databázový mechanismus zapouzdření cizích dat (Foreign Data Wrappers). Díky tomu se mohou cizí data jevit jako součást vlastní databáze a je možné s nimi pracovat jako s pohledy. Tento druh provázání se hodí zejména pro čerpání z rozsáhlých databází, které není výhodné přenášet celé.

[plantuml,align="center"]
....
@startuml
left to right direction

package "SpIS" {
  database "DB" as db1
}

package "Cizí systém" {
  component "Aplikace" as app2
  () API as api2
  app2 - api2
}

db1 -> api2: FDW
@enduml
....


===== Data z dokumentů

Žádná existující databáze zatím neobsahuje funkci automatického, okamžitého odvozování tabulek a reakci na změny takto odvozených řádků. Pro naplnění relačních datových struktur z dokumentů se tak využívají spouště, které data z dokumentů přenáší do tabulek ihned po vytvoření nové revize nebo změně stavu dokumentu.

Různé přehledy mohou mít různé požadavky na platnost revizí dokumentů, ze kterých čerpají. Mohou vyžadovat revizi nejnovější, poslední podepsanou, obě zároveň nebo jejich spojení. Vhodná soustava pohledů usnadní jejich vytváření.


=== Uživatelské rozhraní

WARNING: REST API, webové rozhraní...


// vim:set spelllang=cs:
