== Popis procesu plánování rozpočtu na IPR

1. Pro každý **Výdaj**, který má být zahrnut do plánovaného rozpočtu, je vypracován samostatný **Dokument**, který poskytuje veškeré potřebné údaje pro registraci **Výdaje**.
2. Jednotlivé **Výdaje** jsou posléze dohledatelné skrze přednastavené **Pohledy** (_Seznam aktivních zakázek_ a _Seznam plánovaných zakázek_), které slouží jako podklady pro přípravu návrhu rozpočtu sekce a jejích kanceláří.
3. Z těchto **Pohledů** je následně vytvořen další nadřazený **Pohled** (případně více různých **Pohledů**, je-li to žádoucí), který je exportován do **Dokumentu** _Návrh dílčího rozpočtu_, který sestavuje vedoucí sekce (nebo k tomu pověřená osoba) žádající o registraci rozpočtu.
4. V **Případu** _Příprava rozpočtu_ se shromažďují _Návrhy dílčího rozpočtu_ od vedoucích jednotlivých sekcí (nebo k tomu pověřených osob), které si následně převezme ekonom organizace (rozpočtář).
5. Převzaté _Návrhy dílčího rozpočtu_ ekonom organizace (rozpočtář) zkoriguje a upraví v **Dokumentu** _Rozpočet_.
6. **Dokument** _Rozpočet_ je předán ke schválení nadřízenému orgánu.

== Rozpočet, změny rozpočtu a přehled čerpání
Rozpočet schválený zřizovatelem je závazný pro plánování a přehled čerpání přidělených financí. Částky schválené zřizovatelem rozdělí ekonom organizace (rozpočtář) zpětně mezi jednotlivé sekce dle účelu využití. Přidělené částky jsou závazné pro všechny uživatele jako limity čerpání, jejich změnu smí provést pouze správce rozpočtu na základě usnesení rady MHMP o změně rozpočtu.
V IPR je možné v rámci limitů čerpání přerozdělovat finance mezi sekcemi a měnit účel jejich vynaložení. Tyto změny může provádět pouze správce rozpočtu a jsou schvalovány vedoucími sekcí dotčených změnami.

== Specifické požadavky na modul Rozpočet

1. Sestavy rozpočtu obsahují přehledové tabulky, které se dynamicky mění a přepočítávají dle vyfiltrovaných položek v seznamu a ukazují souhrnné částky dle vybraných témat.
2. V rámci implementační analýzy bude řešen způsob prezentace a zásahu do rozpočtu projektů financovaných částečně z externích zdrojů - jedná se o projekty TAČR, EU apod., u kterých se peníze proplácejí zpětně.
3. Obsahem implementační analýzy bude způsob řešení hierarchického uspořádání záměr/zakázka/spolupráce sekcí/rámcová smlouva. Jeden záměr vždy generuje 1 zakázku či rámcovou smlouvu, jejíž součástí ale může být více podzakázek (objednávek). Každou objednávku může garantovat a financovat jiná sekce v rámci IPR. Taktéž u zakázky může být každá etapa financována a garantována jinou sekcí.
